name: i am uberman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dadada'
    - '#ffffff'
    - '#000000'
    - '#6a6a6a'
    - '#a4a4a4'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
