name: i am uberman
favicon: null
layout_spectrum: 0.6406581364572048
typography_spectrum: 0.2901974390260875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.33172309934161603
  lightness: 0.8258465656545013
  saturation: 0.9176154620945454
  rhythmicContrast: 0.6009721509180963
purpose: []
